version: '3.7'

services:
  fullstack:
    image: ghcr.io/ginnjo/fullstack/fullstack
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongo

services:
  nomad:
    image: multani/nomad
    command: agent
    privileged: true
    network_mode: "host"
    environment:
      NOMAD_LOCAL_CONFIG: |
        datacenter = "dc1"
        data_dir = "/opt/nomad/data"
        bind_addr = "0.0.0.0"
    volumes:
      - nomad_data:/nomad/data/

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fullstack

  mongo:
    image: mongo
    restart: always

    volumes:
      - mongo_data:/data/db
  
    ports:
      - "27017:27017"

#    environment:
#      MONGO_INITDB_ROOT_USERNAME: your_username
#      MONGO_INITDB_ROOT_PASSWORD: your_password

volumes:
  caddy_data:
  caddy_config:
  mongo_data:
  nomad_data:
